### ISSUE TITLE
Upcoming breaking changes (v12)

### ISSUE THREAD

**Issue by adnasa** [commercetools/ui-kit#1737]
## Summary

- [x] #1827 Drop Table
`<Table />` component has been deprecated in favor of `<DataTable />`. [reference](https://jira.commercetools.com/browse/UKIT-186)
- [x] #1828 Drop deprecated prop `constraint` on `Constraints.Horizontal` in favor of `max`. [reference](https://wiki.commercetools.com/display/shield/2020/11/17/New+Constraints+Scale)
- [x] #1825 Move RichTextEdit/LocalizedRichTextEditor out of beta [reference](https://jira.commercetools.com/browse/UKIT-194) 
- [x] #1824 Drop deprecated props on `Text` component
The `Text` component has a handful of deprecated props, such as `elementType` and `isInline`
- [x] #1826 Drop `hasUnderline` from `Link` (see #1548)
- [x] #1830 Drop deprecated prop `linkTo` in `SecondayButton`
  - remove `linkTo` from `<Tag />`

**Comment by tdeekens** [comment]
Controversial maybe but we could attempt (or suggest) to product to remove the `RichTextEdit`. I think no customer currently uses it. Less code is good code. Should be verified with the respective team I think.

**Comment by adnasa** [comment]
> Should be verified with the respective team I think.

true. We also have to check if there are plans on using these.

**Comment by tdeekens** [comment]
> > Should be verified with the respective team I think.
> 
> true. We also have to check if there are plans on using these.

Quickly reached out to the team. They're using it with more customers by now. They're also planning to roll it out in general but want to do so with receiving customer feedback in the process. As a result we should keep it. Thanks.
